=== JonSaffron/Labyrinth/LabyrinthContent/Worlds/WorldSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema targetNamespace="http://JonSaffron/Labyrinth" elementFormDefault="qualified" xmlns="http://JonSaffron/Labyrinth" xmlns:mstns="http://tempuri.org/XMLSchema.xsd" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="World">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Layout" type="xs:string" minOccurs="1" maxOccurs="1" />
        <xs:element name="Areas" type="Areas" minOccurs="1" maxOccurs="1" />
        <xs:element name="Objects" type="Objects" minOccurs="0" maxOccurs="1" />
      </xs:sequence>
      <xs:attribute name="Name" type="xs:string" use="required" />
      <xs:attribute name="Height" type="xs:int" use="required" />
      <xs:attribute name="Width" type="xs:int" use="required" />
      <xs:attribute name="RestartInSameRoom" type="xs:boolean" use="optional" default="false" />
      <xs:attribute name="UnlockLevels" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>
  </xs:element>
  
  <xs:complexType name="Areas">
    <xs:sequence>
      <xs:element name="Area" type="Area" minOccurs="0" maxOccurs="unbounded" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Area">
    <xs:sequence>
      <xs:element name="PlayerStartState" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:attribute name="Id" type="xs:int" use="required" />
          <xs:attribute name="WorldStart" type="xs:boolean" use="optional" default="false" />
          <xs:attribute name="Left" type="xs:int" use="required" />
          <xs:attribute name="Top" type="xs:int" use="required" />
          <xs:attribute name="Energy" type="xs:int" use="required" />
        </xs:complexType>
      </xs:element>

      <xs:element name="TileDefinitions" minOccurs="0" maxOccurs="1" >
        <xs:complexType>
          <xs:choice maxOccurs="unbounded">
            <xs:element name="Wall" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="Symbol" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:length value="1" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
                
                <xs:attribute name="Tile" type="xs:string" use="required" />
              </xs:complexType>
            </xs:element>

            <xs:element name="Floor" minOccurs="1" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="Symbol" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:length value="1" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>

                <xs:attribute name="Tile" type="xs:string" use="required" />

                <xs:attribute name="Default" type="xs:boolean" use="optional" default="false" />
              </xs:complexType>
            </xs:element>

            <xs:element name="Object" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="Symbol" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:length value="1" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>

                <xs:attribute name="Description" type="xs:string" use="required" />
              </xs:complexType>
            </xs:element>
          </xs:choice>
        </xs:complexType>
      </xs:element>

      <xs:element name="FruitDefinitions" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="FruitDef" minOccurs="0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:attribute name="Type" type="xs:string" use="required" />
                <xs:attribute name="Quantity" type="xs:int" use="required" />
                <xs:attribute name="Energy" type="xs:int" use="required" />
              </xs:complexType>
            </xs:element>
          </xs:sequence>

          <xs:attribute name="PopulationMethod" use="required">
            <xs:simpleType>
              <xs:restriction base="xs:string">
                <xs:enumeration value="InitialPopulationOnly" />
                <xs:enumeration value="GradualPopulation" />
                <xs:enumeration value="InitialPopulationWithReplenishment" />
              </xs:restriction>
            </xs:simpleType>
          </xs:attribute>
        </xs:complexType>
      </xs:element>

      <xs:element name="RandomMonsterDistribution" minOccurs="0" maxOccurs="1">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="MonsterTemplates" minOccurs="1" maxOccurs="1" >
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="Monster" type="MonsterTemplateDef" minOccurs="1" maxOccurs="unbounded" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
          </xs:sequence>
          <xs:attribute name="DiceToRoll" type="xs:string" use="required" />
          <xs:attribute name="CountOfMonsters" type="xs:int" use="required" />
        </xs:complexType>
      </xs:element>
    </xs:sequence>
    
    <xs:attribute name="Top" type="xs:int" use="required" />
    <xs:attribute name="Left" type="xs:int" use="required" />
    <xs:attribute name="Width" type="xs:int" use="required" />
    <xs:attribute name="Height" type="xs:int" use="required" />
  </xs:complexType>
  
  <xs:complexType name="Objects">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element name="Boulder" >
        <xs:complexType>
          <xs:attribute name="Left" type="xs:int" use="required" />
          <xs:attribute name="Top" type="xs:int" use="required" />
        </xs:complexType>
      </xs:element>

      <xs:element name="Crystal">
        <xs:complexType>
          <xs:attribute name="Left" type="xs:int" use="required" />
          <xs:attribute name="Top" type="xs:int" use="required" />
          <xs:attribute name="Id" type="xs:int" use="required" />
          <xs:attribute name="Score" type="xs:int" use="required" />
          <xs:attribute name="Energy" type="xs:int" use="required" />
        </xs:complexType>
      </xs:element>

      <xs:element name="CrumblyWall">
        <xs:complexType>
          <xs:attribute name="Left" type="xs:int" use="required" />
          <xs:attribute name="Top" type="xs:int" use="required" />
          <xs:attribute name="Energy" type="xs:int" use="required" />
          <xs:attribute name="Texture" type="xs:string" use="required" />
        </xs:complexType>
      </xs:element>
      
      <xs:element name="ForceField">
        <xs:complexType>
          <xs:attribute name="Left" type="xs:int" use="required" />
          <xs:attribute name="Top" type="xs:int" use="required" />
          <xs:attribute name="Width" type="xs:int" use="required" />
          <xs:attribute name="Height" type="xs:int" use="required" />
          <xs:attribute name="CrystalRequired" type="xs:int" use="required" />
        </xs:complexType>
      </xs:element>

      <xs:element name="Monster" type="MonsterInstance" />
    </xs:choice>
  </xs:complexType>

  <xs:complexType name="MonsterInstance">
    <xs:complexContent>
      <xs:extension base="MonsterBase">
        <xs:attribute name="Left" type="xs:int" use="required" />
        <xs:attribute name="Top" type="xs:int" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="MonsterTemplateDef">
    <xs:complexContent>
      <xs:extension base="MonsterBase">
        <xs:attribute name="MatchingDiceRoll" type="xs:int" use="required" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

  <xs:complexType name="MonsterBase">
    <xs:all>
      <xs:element name="Apply" minOccurs="0">
        <xs:complexType>
          <xs:all>
            <xs:element name="MobilityAfterInjury" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="value" use="required" type="MonsterMobilitySubsequent" />
              </xs:complexType>
            </xs:element>

            <xs:element name="ChangeRoomsAfterInjury" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="value" use="required" type="ChangeRooms" />
              </xs:complexType>
            </xs:element>

            <xs:element name="IsEgg" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="TimeBeforeHatching" use="required" type="xs:int" />
              </xs:complexType>
            </xs:element>

            <xs:element name="LaysEggs" minOccurs="0" />

            <xs:element name="LaysMushrooms" minOccurs="0" />

            <xs:element name="SplitsOnHit" minOccurs="0" />

            <xs:element name="ShootsAtPlayer" minOccurs="0">
              <xs:complexType>
                <xs:attribute name="value" use="required">
                  <xs:simpleType>
                    <xs:restriction base="xs:string">
                      <xs:enumeration value="Immediately" />
                      <xs:enumeration value="OnceInjured" />
                    </xs:restriction>
                  </xs:simpleType>
                </xs:attribute>
              </xs:complexType>
            </xs:element>

            <xs:element name="ShotsBounceOff" minOccurs="0" />
          </xs:all>
        </xs:complexType>
      </xs:element>
      <xs:element name="Remove" minOccurs="0">
        <xs:complexType>
          <xs:all>
            <xs:element name="MobilityAfterInjury" minOccurs="0" />
            <xs:element name="ChangeRoomsAfterInjury" minOccurs="0" />
            <xs:element name="LaysEggs" minOccurs="0" />
            <xs:element name="LaysMushrooms" minOccurs="0" />
            <xs:element name="SplitsOnHit" minOccurs="0" />
            <xs:element name="ShootsAtPlayer" minOccurs="0" />
            <xs:element name="ShotsBounceOff" minOccurs="0" />
          </xs:all>
        </xs:complexType>
      </xs:element>
    </xs:all>

    <xs:attribute name="Breed" type="xs:string" use="required" />
    <xs:attribute name="Energy" type="xs:int" use="required" />
    <xs:attribute name="Mobility" use="optional" type="MonsterMobility" />
    <xs:attribute name="InitialDirection" use="optional" type="Direction" />
    <xs:attribute name="ChangeRooms" use="optional" type="ChangeRooms" />
    <xs:attribute name="IsActive" type="xs:boolean" use="optional" />
  </xs:complexType>

  <xs:simpleType name="MonsterMobilityInitial">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Stationary" />
      <xs:enumeration value="Patrolling" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MonsterMobilitySubsequent">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Placid" />
      <xs:enumeration value="Aggressive" />
      <xs:enumeration value="Cautious" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="MonsterMobility">
    <xs:union memberTypes="MonsterMobilityInitial MonsterMobilitySubsequent" />
  </xs:simpleType>

  <xs:simpleType name="Direction">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Left" />
      <xs:enumeration value="Right" />
      <xs:enumeration value="Up" />
      <xs:enumeration value="Down" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="ChangeRooms">
    <xs:restriction base="xs:string">
      <xs:enumeration value="StaysWithinRoom" />
      <xs:enumeration value="MovesRoom" />
      <xs:enumeration value="FollowsPlayer" />
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== JonSaffron/Labyrinth/LabyrinthContent/Worlds/TestWorld.xml
<?xml version="1.0" encoding="utf-8" ?>
<World Name="TestWorld" Height="20" Width="32" xmlns="http://JonSaffron/Labyrinth" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://JonSaffron/Labyrinth WorldSchema.xsd">
  <Layout>
    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
    OS       #     OO              O
    O        #P    OO              O
    O        ######OO              O
    O                              O
    O                              O
    O              OO              O
    O              OO              O
    O              OO              O
    OOOOOO    OOOOOOOOOOO    OOOOOOO
    OOOOOO    OOOOOOOOOOO    OOOOOOO
    O              OO              O
    O              OO              O
    O              OO              O
    O                              O
    O                              O
    O              OO              O
    O              OO              O
    O              OO             CO
    OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO
  </Layout>
  <Areas>
    <Area Top="0" Left="0" Width="32" Height="20">
      <PlayerStartState Id="1" Left="1" Top="1" Energy="50" WorldStart="true"/>
      <TileDefinitions>
        <Wall Symbol="O" Tile="Wall3Full" />
        <Floor Symbol=" " Tile="Floor3" />
        <Object Symbol="S" Description="Player Start" />
        <Object Symbol="C" Description="Crystal" />
        <Object Symbol="P" Description="PatrolPerimiterTest" />
        <Object Symbol="#" Description="CrumblyWall" />
      </TileDefinitions>
    </Area>
  </Areas>
  
  <Objects>
    <Crystal Id="1" Energy="100" Left="30" Top="18" Score="1000"/>
    <CrumblyWall Energy="20" Left="9" Top="1" Texture="CrumblyWall3" />
    <CrumblyWall Energy="20" Left="9" Top="2" Texture="CrumblyWall3" />
    <CrumblyWall Energy="20" Left="9" Top="3" Texture="CrumblyWall3" />
    <CrumblyWall Energy="20" Left="10" Top="3" Texture="CrumblyWall3" />
    <CrumblyWall Energy="20" Left="11" Top="3" Texture="CrumblyWall3" />
    <CrumblyWall Energy="20" Left="12" Top="3" Texture="CrumblyWall3" />
    <CrumblyWall Energy="20" Left="13" Top="3" Texture="CrumblyWall3" />
    <CrumblyWall Energy="20" Left="14" Top="3" Texture="CrumblyWall3" />
    <Monster Type="PatrolPerimiterTest" Left="10" Top="2" Energy="10" Mobility="Patrolling" InitialDirection="Right" ChangeRooms="MovesRoom" />
  </Objects>
</World>
